<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>applicationIcon.ico</ApplicationIcon>

		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>    
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="OldApplicationIcon.ico" />
		<Resource Include="ApplicationIcon.ico" />
		<Resource Include="FluentSystemIcons-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.0" />
		<PackageReference Include="System.IO.Abstractions" Version="21.0.2" />
		<PackageReference Include="WPF-UI" Version="3.0.4" />
	</ItemGroup>

</Project>
